### ISSUE TITLE
Hitting "-" with a public link

### ISSUE THREAD

**Issue by realriot** [a-zb/dropfuse#6]
Providing a public link with a "-" in it the dropfuse.py will exit with:

Traceback (most recent call last):
  File "dropfuse.py", line 181, in <module>
    dropfuse = FUSE(DropFuse(link, argv[2]), argv[2],
  File "dropfuse.py", line 86, in **init**
    self.client.parse(s)
  File "dropfuse.py", line 38, in parse
    filesize = self.getSize()
  File "dropfuse.py", line 52, in getSize
    num, var = size.split(" ")
ValueError: need more than 1 value to unpack

Tested with: https://www.dropbox.com/sh/pt93r93b2widzgn/-6q8ZVy9ug

**Comment by a-zb** [comment]
Line 52 is not related to a dash in a URL and that URL doesn't look right as well.
Dropbox reports it as missing or moved.

Is that a link to a shared folder ?

Please provide a test URL.

If you would like to test it yourself, Install FireBug extension in Firefox and run the following
piece of code in the Console tab while the shared folder is displayed in the browser
    jQuery('div.filesize-col span.size').text();

You should see something like this:
    "2.25 MB2 bytes1.45 KB732 bytes"

You can test it first on my shared folder: https://www.dropbox.com/s/c6ecc2plwconh5x

**Comment by realriot** [comment]
Ok, had a console problem.

**Comment by cefn** [comment]
I seem to be having a different kind of problem, but with the same behaviour.

I ran pdb dropfuse.py "https://www.dropbox.com/sh/ixrt14yp97xvn6v/AADevw31m1U9RiFEem87OH5na?dl=0" "/home/cefn/Documents/highwire/participatory\ firmware\ design/readinglog/papers/"

The document which comes back (from lxml.etree.tostring()) from the subfolder link shared above looks like...

`(Pdb) etree.tostring(self.file)
'<li class="browse-file list-view-cols"><div class="filename-col"><a href="https://www.dropbox.com/sh/ixrt14yp97xvn6v/AADe4GTOAjobhn6VZ0pXbMQka/shortened?dl=0?lst" target="_top" rel="nofollow" class="thumb-link"><img src="https://dt8kf6553cww8.cloudfront.net/static/images/icons/icon_spacer-vflN3BYt2.gif" class="s_web_folder_32 sprite sprite_web icon"/></a><div class="filename"><a href="https://www.dropbox.com/sh/ixrt14yp97xvn6v/AADe4GTOAjobhn6VZ0pXbMQka/shortened?dl=0?lst" target="_top" rel="nofollow" class="filename-link"><span id="pyxl3259941315460918484"/></a></div></div><div class="filesize-col"><span class="size">--</span></div><div class="modified-col"><span><span class="modified-time">--</span></span></div><br class="clear"/></li>'`

SO consequently the following results...
`(Pdb) self.pq_file.find('div.filesize-col span.size').text()
'--'`

This is fatal to completing the mount process and the command fails.

**Comment by a-zb** [comment]
Thanks for the report.

I'll take a look at it. Once I can isolate the issue and reproduce it,I will create a new issue on GH and it will be managed there.
